/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllExpenseCategories } from '../fn/bank-statement-controller/get-all-expense-categories';
import { GetAllExpenseCategories$Params } from '../fn/bank-statement-controller/get-all-expense-categories';
import { getCategoryWiseTotalExpense } from '../fn/bank-statement-controller/get-category-wise-total-expense';
import { GetCategoryWiseTotalExpense$Params } from '../fn/bank-statement-controller/get-category-wise-total-expense';
import { getMonthWiseExpenseReport } from '../fn/bank-statement-controller/get-month-wise-expense-report';
import { GetMonthWiseExpenseReport$Params } from '../fn/bank-statement-controller/get-month-wise-expense-report';
import { getSpecificCategoryTransactions } from '../fn/bank-statement-controller/get-specific-category-transactions';
import { GetSpecificCategoryTransactions$Params } from '../fn/bank-statement-controller/get-specific-category-transactions';
import { getTransactions } from '../fn/bank-statement-controller/get-transactions';
import { GetTransactions$Params } from '../fn/bank-statement-controller/get-transactions';
import { Transaction } from '../models/transaction';
import { TransactionResponse } from '../models/transaction-response';

@Injectable({ providedIn: 'root' })
export class BankStatementControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMonthWiseExpenseReport()` */
  static readonly GetMonthWiseExpenseReportPath = '/account/statement/transactions/monthwise/expense';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMonthWiseExpenseReport()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getMonthWiseExpenseReport$Response(params?: GetMonthWiseExpenseReport$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
[key: string]: {
};
};
}>> {
    return getMonthWiseExpenseReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMonthWiseExpenseReport$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getMonthWiseExpenseReport(params?: GetMonthWiseExpenseReport$Params, context?: HttpContext): Observable<{
[key: string]: {
[key: string]: {
};
};
}> {
    return this.getMonthWiseExpenseReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
[key: string]: {
};
};
}>): {
[key: string]: {
[key: string]: {
};
};
} => r.body)
    );
  }

  /** Path part for operation `getCategoryWiseTotalExpense()` */
  static readonly GetCategoryWiseTotalExpensePath = '/account/statement/transactions/category/totalexpense';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryWiseTotalExpense()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getCategoryWiseTotalExpense$Response(params?: GetCategoryWiseTotalExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getCategoryWiseTotalExpense(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryWiseTotalExpense$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getCategoryWiseTotalExpense(params?: GetCategoryWiseTotalExpense$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getCategoryWiseTotalExpense$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `getTransactions()` */
  static readonly GetTransactionsPath = '/account/statement/transactions/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTransactions()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getTransactions$Response(params?: GetTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
    return getTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTransactions$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getTransactions(params?: GetTransactions$Params, context?: HttpContext): Observable<Array<TransactionResponse>> {
    return this.getTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransactionResponse>>): Array<TransactionResponse> => r.body)
    );
  }

  /** Path part for operation `getSpecificCategoryTransactions()` */
  static readonly GetSpecificCategoryTransactionsPath = '/account/statement/transactions/category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSpecificCategoryTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecificCategoryTransactions$Response(params: GetSpecificCategoryTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Transaction>>> {
    return getSpecificCategoryTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSpecificCategoryTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecificCategoryTransactions(params: GetSpecificCategoryTransactions$Params, context?: HttpContext): Observable<Array<Transaction>> {
    return this.getSpecificCategoryTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Transaction>>): Array<Transaction> => r.body)
    );
  }

  /** Path part for operation `getAllExpenseCategories()` */
  static readonly GetAllExpenseCategoriesPath = '/account/statement/expensecategories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllExpenseCategories()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExpenseCategories$Response(params?: GetAllExpenseCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return getAllExpenseCategories(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllExpenseCategories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExpenseCategories(params?: GetAllExpenseCategories$Params, context?: HttpContext): Observable<Array<string>> {
    return this.getAllExpenseCategories$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
