/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllExpenseCategories1 } from '../fn/bank-statement-controller/get-all-expense-categories-1';
import { GetAllExpenseCategories1$Params } from '../fn/bank-statement-controller/get-all-expense-categories-1';
import { getCategoryWiseTotalExpense1 } from '../fn/bank-statement-controller/get-category-wise-total-expense-1';
import { GetCategoryWiseTotalExpense1$Params } from '../fn/bank-statement-controller/get-category-wise-total-expense-1';
import { getMonthWiseExpenseReport1 } from '../fn/bank-statement-controller/get-month-wise-expense-report-1';
import { GetMonthWiseExpenseReport1$Params } from '../fn/bank-statement-controller/get-month-wise-expense-report-1';
import { getSpecificCategoryTransactions1 } from '../fn/bank-statement-controller/get-specific-category-transactions-1';
import { GetSpecificCategoryTransactions1$Params } from '../fn/bank-statement-controller/get-specific-category-transactions-1';
import { getSpecificMonthTransactions1 } from '../fn/bank-statement-controller/get-specific-month-transactions-1';
import { GetSpecificMonthTransactions1$Params } from '../fn/bank-statement-controller/get-specific-month-transactions-1';
import { getTransactions1 } from '../fn/bank-statement-controller/get-transactions-1';
import { GetTransactions1$Params } from '../fn/bank-statement-controller/get-transactions-1';
import { saveTransactions } from '../fn/bank-statement-controller/save-transactions';
import { SaveTransactions$Params } from '../fn/bank-statement-controller/save-transactions';
import { Transaction } from '../models/transaction';
import { TransactionResponse } from '../models/transaction-response';

@Injectable({ providedIn: 'root' })
export class BankStatementControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveTransactions()` */
  static readonly SaveTransactionsPath = '/account/statement/transactions/save';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  saveTransactions$Response(params?: SaveTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return saveTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  saveTransactions(params?: SaveTransactions$Params, context?: HttpContext): Observable<void> {
    return this.saveTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getSpecificMonthTransactions1()` */
  static readonly GetSpecificMonthTransactions1Path = '/account/statement/transactions/save/{month}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSpecificMonthTransactions1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getSpecificMonthTransactions1$Response(params?: GetSpecificMonthTransactions1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
    return getSpecificMonthTransactions1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSpecificMonthTransactions1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getSpecificMonthTransactions1(params?: GetSpecificMonthTransactions1$Params, context?: HttpContext): Observable<Array<TransactionResponse>> {
    return this.getSpecificMonthTransactions1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransactionResponse>>): Array<TransactionResponse> => r.body)
    );
  }

  /** Path part for operation `getMonthWiseExpenseReport1()` */
  static readonly GetMonthWiseExpenseReport1Path = '/account/statement/transactions/monthwise/expense';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMonthWiseExpenseReport1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getMonthWiseExpenseReport1$Response(params?: GetMonthWiseExpenseReport1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
[key: string]: {
};
};
}>> {
    return getMonthWiseExpenseReport1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMonthWiseExpenseReport1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getMonthWiseExpenseReport1(params?: GetMonthWiseExpenseReport1$Params, context?: HttpContext): Observable<{
[key: string]: {
[key: string]: {
};
};
}> {
    return this.getMonthWiseExpenseReport1$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
[key: string]: {
};
};
}>): {
[key: string]: {
[key: string]: {
};
};
} => r.body)
    );
  }

  /** Path part for operation `getCategoryWiseTotalExpense1()` */
  static readonly GetCategoryWiseTotalExpense1Path = '/account/statement/transactions/category/totalexpense';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryWiseTotalExpense1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getCategoryWiseTotalExpense1$Response(params?: GetCategoryWiseTotalExpense1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getCategoryWiseTotalExpense1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryWiseTotalExpense1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getCategoryWiseTotalExpense1(params?: GetCategoryWiseTotalExpense1$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getCategoryWiseTotalExpense1$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `getTransactions1()` */
  static readonly GetTransactions1Path = '/account/statement/transactions/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTransactions1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getTransactions1$Response(params?: GetTransactions1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
    return getTransactions1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTransactions1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getTransactions1(params?: GetTransactions1$Params, context?: HttpContext): Observable<Array<TransactionResponse>> {
    return this.getTransactions1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransactionResponse>>): Array<TransactionResponse> => r.body)
    );
  }

  /** Path part for operation `getSpecificCategoryTransactions1()` */
  static readonly GetSpecificCategoryTransactions1Path = '/account/statement/transactions/category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSpecificCategoryTransactions1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecificCategoryTransactions1$Response(params: GetSpecificCategoryTransactions1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Transaction>>> {
    return getSpecificCategoryTransactions1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSpecificCategoryTransactions1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecificCategoryTransactions1(params: GetSpecificCategoryTransactions1$Params, context?: HttpContext): Observable<Array<Transaction>> {
    return this.getSpecificCategoryTransactions1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Transaction>>): Array<Transaction> => r.body)
    );
  }

  /** Path part for operation `getAllExpenseCategories1()` */
  static readonly GetAllExpenseCategories1Path = '/account/statement/expensecategories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllExpenseCategories1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExpenseCategories1$Response(params?: GetAllExpenseCategories1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return getAllExpenseCategories1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllExpenseCategories1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExpenseCategories1(params?: GetAllExpenseCategories1$Params, context?: HttpContext): Observable<Array<string>> {
    return this.getAllExpenseCategories1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
