/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionResponse {
  closingBalance?: string;
  creditAmount?: number;
  debitAmount?: number;
  narration?: string;
  refNumber?: string;
  transactionDate?: string;
  transactionType?: string;
}
