/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankStatement } from '../models/bank-statement';
export interface Transaction {
  bankStatement?: BankStatement;
  closingBalance?: string;
  creditAmount?: number;
  debitAmount?: number;
  id?: number;
  narration?: string;
  refNumber?: string;
  transactionCategory?: string;
  transactionDate?: string;
  transactionType?: string;
}
