/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { StatementControllerService } from './services/statement-controller.service';
export { BankStatementControllerService } from './services/bank-statement-controller.service';
