/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BankStatement } from '../../models/bank-statement';

export interface GetAllBankStatement$Params {
}

export function getAllBankStatement(http: HttpClient, rootUrl: string, params?: GetAllBankStatement$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BankStatement>>> {
  const rb = new RequestBuilder(rootUrl, getAllBankStatement.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BankStatement>>;
    })
  );
}

getAllBankStatement.PATH = '/bank/account/statement/all';
