/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionResponse } from '../../models/transaction-response';

export interface SaveBankStatement$Params {
  bankName: string;
      body: Array<TransactionResponse>
}

export function saveBankStatement(http: HttpClient, rootUrl: string, params: SaveBankStatement$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, saveBankStatement.PATH, 'post');
  if (params) {
    rb.path('bankName', params.bankName, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

saveBankStatement.PATH = '/bank/account/statement/transactions/bankstatement/save/{bankName}';
