/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionResponse } from '../../models/transaction-response';

export interface GetSpecificMonthTransactions1$Params {
      body?: {
'document': Blob;
'month'?: string;
}
}

export function getSpecificMonthTransactions1(http: HttpClient, rootUrl: string, params?: GetSpecificMonthTransactions1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
  const rb = new RequestBuilder(rootUrl, getSpecificMonthTransactions1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TransactionResponse>>;
    })
  );
}

getSpecificMonthTransactions1.PATH = '/account/statement/transactions/save/{month}';
