/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BankStatement } from '../models/bank-statement';
import { getAllBankStatement } from '../fn/statement-controller/get-all-bank-statement';
import { GetAllBankStatement$Params } from '../fn/statement-controller/get-all-bank-statement';
import { getAllExpenseCategories } from '../fn/statement-controller/get-all-expense-categories';
import { GetAllExpenseCategories$Params } from '../fn/statement-controller/get-all-expense-categories';
import { getCategoryWiseTotalExpense } from '../fn/statement-controller/get-category-wise-total-expense';
import { GetCategoryWiseTotalExpense$Params } from '../fn/statement-controller/get-category-wise-total-expense';
import { getMonthWiseExpenseReport } from '../fn/statement-controller/get-month-wise-expense-report';
import { GetMonthWiseExpenseReport$Params } from '../fn/statement-controller/get-month-wise-expense-report';
import { getSpecificCategoryTransactions } from '../fn/statement-controller/get-specific-category-transactions';
import { GetSpecificCategoryTransactions$Params } from '../fn/statement-controller/get-specific-category-transactions';
import { getSpecificMonthTransactions } from '../fn/statement-controller/get-specific-month-transactions';
import { GetSpecificMonthTransactions$Params } from '../fn/statement-controller/get-specific-month-transactions';
import { getTransactions } from '../fn/statement-controller/get-transactions';
import { GetTransactions$Params } from '../fn/statement-controller/get-transactions';
import { saveBankStatement } from '../fn/statement-controller/save-bank-statement';
import { SaveBankStatement$Params } from '../fn/statement-controller/save-bank-statement';
import { TransactionResponse } from '../models/transaction-response';

@Injectable({ providedIn: 'root' })
export class StatementControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getSpecificMonthTransactions()` */
  static readonly GetSpecificMonthTransactionsPath = '/bank/account/statement/transactions/save/{bankName}/{month}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSpecificMonthTransactions()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getSpecificMonthTransactions$Response(params: GetSpecificMonthTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
    return getSpecificMonthTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSpecificMonthTransactions$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getSpecificMonthTransactions(params: GetSpecificMonthTransactions$Params, context?: HttpContext): Observable<Array<TransactionResponse>> {
    return this.getSpecificMonthTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransactionResponse>>): Array<TransactionResponse> => r.body)
    );
  }

  /** Path part for operation `getMonthWiseExpenseReport()` */
  static readonly GetMonthWiseExpenseReportPath = '/bank/account/statement/transactions/monthwise/expense/{bankName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMonthWiseExpenseReport()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getMonthWiseExpenseReport$Response(params: GetMonthWiseExpenseReport$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
[key: string]: {
};
};
}>> {
    return getMonthWiseExpenseReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMonthWiseExpenseReport$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getMonthWiseExpenseReport(params: GetMonthWiseExpenseReport$Params, context?: HttpContext): Observable<{
[key: string]: {
[key: string]: {
};
};
}> {
    return this.getMonthWiseExpenseReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
[key: string]: {
};
};
}>): {
[key: string]: {
[key: string]: {
};
};
} => r.body)
    );
  }

  /** Path part for operation `getCategoryWiseTotalExpense()` */
  static readonly GetCategoryWiseTotalExpensePath = '/bank/account/statement/transactions/category/totalexpense/{bankName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryWiseTotalExpense()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getCategoryWiseTotalExpense$Response(params: GetCategoryWiseTotalExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getCategoryWiseTotalExpense(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryWiseTotalExpense$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getCategoryWiseTotalExpense(params: GetCategoryWiseTotalExpense$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getCategoryWiseTotalExpense$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `saveBankStatement()` */
  static readonly SaveBankStatementPath = '/bank/account/statement/transactions/bankstatement/save/{bankName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveBankStatement()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBankStatement$Response(params: SaveBankStatement$Params, context?: HttpContext): Observable<StrictHttpResponse<BankStatement>> {
    return saveBankStatement(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveBankStatement$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBankStatement(params: SaveBankStatement$Params, context?: HttpContext): Observable<BankStatement> {
    return this.saveBankStatement$Response(params, context).pipe(
      map((r: StrictHttpResponse<BankStatement>): BankStatement => r.body)
    );
  }

  /** Path part for operation `getTransactions()` */
  static readonly GetTransactionsPath = '/bank/account/statement/all/transactions/{bankName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTransactions()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getTransactions$Response(params: GetTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
    return getTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTransactions$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  getTransactions(params: GetTransactions$Params, context?: HttpContext): Observable<Array<TransactionResponse>> {
    return this.getTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransactionResponse>>): Array<TransactionResponse> => r.body)
    );
  }

  /** Path part for operation `getSpecificCategoryTransactions()` */
  static readonly GetSpecificCategoryTransactionsPath = '/bank/account/statement/transactions/category{bankName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSpecificCategoryTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecificCategoryTransactions$Response(params: GetSpecificCategoryTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
    return getSpecificCategoryTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSpecificCategoryTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecificCategoryTransactions(params: GetSpecificCategoryTransactions$Params, context?: HttpContext): Observable<Array<TransactionResponse>> {
    return this.getSpecificCategoryTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransactionResponse>>): Array<TransactionResponse> => r.body)
    );
  }

  /** Path part for operation `getAllExpenseCategories()` */
  static readonly GetAllExpenseCategoriesPath = '/bank/account/statement/expensecategories/{bankName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllExpenseCategories()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExpenseCategories$Response(params: GetAllExpenseCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return getAllExpenseCategories(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllExpenseCategories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExpenseCategories(params: GetAllExpenseCategories$Params, context?: HttpContext): Observable<Array<string>> {
    return this.getAllExpenseCategories$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `getAllBankStatement()` */
  static readonly GetAllBankStatementPath = '/bank/account/statement/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllBankStatement()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBankStatement$Response(params?: GetAllBankStatement$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BankStatement>>> {
    return getAllBankStatement(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllBankStatement$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBankStatement(params?: GetAllBankStatement$Params, context?: HttpContext): Observable<Array<BankStatement>> {
    return this.getAllBankStatement$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BankStatement>>): Array<BankStatement> => r.body)
    );
  }

}
