/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Transaction } from '../../models/transaction';
import { TransactionCategoryRequest } from '../../models/transaction-category-request';

export interface GetSpecificCategoryTransactions$Params {
  transactionCategoryRequest: TransactionCategoryRequest;
}

export function getSpecificCategoryTransactions(http: HttpClient, rootUrl: string, params: GetSpecificCategoryTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Transaction>>> {
  const rb = new RequestBuilder(rootUrl, getSpecificCategoryTransactions.PATH, 'get');
  if (params) {
    rb.query('transactionCategoryRequest', params.transactionCategoryRequest, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Transaction>>;
    })
  );
}

getSpecificCategoryTransactions.PATH = '/account/statement/transactions/category';
