/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileRequest } from '../../models/file-request';
import { Transaction } from '../../models/transaction';

export interface GetAllPdfText$Params {
  fileRequest: FileRequest;
}

export function getAllPdfText(http: HttpClient, rootUrl: string, params: GetAllPdfText$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Transaction>>> {
  const rb = new RequestBuilder(rootUrl, getAllPdfText.PATH, 'get');
  if (params) {
    rb.query('fileRequest', params.fileRequest, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Transaction>>;
    })
  );
}

getAllPdfText.PATH = '/account/statement/transactions/all';
