/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileRequest } from '../../models/file-request';
import { TransactionResponse } from '../../models/transaction-response';

export interface GetAllPdfText$Params {
      body?: FileRequest
}

export function getAllPdfText(http: HttpClient, rootUrl: string, params?: GetAllPdfText$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllPdfText.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TransactionResponse>>;
    })
  );
}

getAllPdfText.PATH = '/account/statement/transactions/all';
